package week_8.q2_agile_waterfall;

import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;

/**
 * See the Lab 8 Questions.md file for the instructions.
 * Don't forget to add screenshots of your program's GUI running.
 */

public class AgileWaterfallGUI extends JFrame {

    private JPanel mainPanel;

    public final static String AGILE = "Agile";
    public final static String WATERFALL = "Waterfall";
    public final static String EITHER = "either";

    public final static String RECOMMENDATION_TEMPLATE = "%s could use %s";

    AgileWaterfallGUI() {
        setContentPane(mainPanel);
        pack();
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setVisible(true);

        //TODO any GUI configuration needed
        //TODO add event handler to read the data entered, and selections made,
        //TODO recommend a methodology, display in JLabel.
        // Use the recommendationTemplate to display a String like "Android App should use Agile"

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
