package week_8.q1_blood_donor;

import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;

/**
 * See the Lab 8 Questions.md file for the instructions.
 * Don't forget to add screenshots of your program's GUI running.
 */


public class DonorGUI extends JFrame {

    public static final String ELIGIBLE = "Eligible!";
    public static final String NOT_ELIGIBLE = "Sorry, not eligible.";
    public static final String INPUT_ERROR = "Error - enter positive numbers";

    private JPanel mainPanel;

    DonorGUI() {
        this.setContentPane(mainPanel);
        pack();
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setVisible(true);

        // TODO add a listener for the checkEligibilityButton
        // This should verify that the user has entered a positive number
        // in both the weightTextField and ageTextField JTextField
        // If either or both are not valid, the resultLable should
        // display the INPUT_ERROR text.

        // If both weight and age are positive numbers, use the data
        // to decide if the user is eligible to be a blood donor.
        // To be eligible, a person must be 17 or older,
        // AND weigh 110 lbs or more.

        // Display the ELIGIBLE text if they are eligible.
        // Display the NOT_ELIGIBLE text if they are not eligible.
        // Use the constants provided in this file.

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
